allow_anonymous true # Damit erlauben wir Verbindungen zum Port 1883 ohne Passwort
listener 1883

# Schaltet Datenspeicherung ein
persistence true
persistence_location /mosquitto/data/

# Leitet Logs in eine Datei weiter
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout